version: "3.6"

services:
  mta-module-builder:
    container_name: mta-server-module-linux-builder
    build: ./docker/mta-server-module-linux-builder
    command: >
      sh -c "yarn"
    volumes:
      - ./:/usr/src/module/
      #- F:/Codes/GitHub/_________MTA__________/mta-gangwar/server/modules/x64/:/usr/src/module/bin/linux/x64/
